// Updated Categories
export const categories = [
  "All",
  "Massage",
  "Servicing",
  "Facials",
  "Cleaning",
  "Beauty",
];

// Expanded Dummy Data (24 items) with Review Counts
export const mockProviders = [
  // --- MASSAGE ---
  {
    id: 1,
    name: "Alice Johnson",
    category: "Massage",
    service: "Deep Tissue Massage",
    rating: 4.8,
    reviewCount: 124,
    price: 850,
    image: "https://i.pravatar.cc/150?img=1",
  },
  {
    id: 2,
    name: "Eva Green",
    category: "Massage",
    service: "Aromatherapy Relaxation",
    rating: 4.7,
    reviewCount: 89,
    price: 700,
    image: "https://i.pravatar.cc/150?img=9",
  },
  {
    id: 3,
    name: "Marcus Thorne",
    category: "Massage",
    service: "Sports Recovery Massage",
    rating: 4.9,
    reviewCount: 215,
    price: 1100,
    image: "https://i.pravatar.cc/150?img=12",
  },
  {
    id: 4,
    name: "Nina Dobrev",
    category: "Massage",
    service: "Hot Stone Therapy",
    rating: 4.5,
    reviewCount: 56,
    price: 950,
    image: "https://i.pravatar.cc/150?img=16",
  },
  {
    id: 5,
    name: "Paul Rudd",
    category: "Massage",
    service: "Quick 30-Min Chair Massage",
    rating: 3.8,
    reviewCount: 210,
    price: 400,
    image: "https://i.pravatar.cc/150?img=33",
  },

  // --- SERVICING ---
  {
    id: 6,
    name: "Bob Smith",
    category: "Servicing",
    service: "AC Repair & Maintenance",
    rating: 3.5,
    reviewCount: 342,
    price: 800,
    image: "https://i.pravatar.cc/150?img=11",
  },
  {
    id: 7,
    name: "David Kim",
    category: "Servicing",
    service: "Plumbing Basics & Leaks",
    rating: 4.2,
    reviewCount: 128,
    price: 1500,
    image: "https://i.pravatar.cc/150?img=8",
  },
  {
    id: 8,
    name: "Hector Salamanca",
    category: "Servicing",
    service: "Electrical Inspection",
    rating: 4.6,
    reviewCount: 75,
    price: 1200,
    image: "https://i.pravatar.cc/150?img=53",
  },
  {
    id: 9,
    name: "Terry Crews",
    category: "Servicing",
    service: "Heavy Furniture Assembly",
    rating: 4.9,
    reviewCount: 512,
    price: 600,
    image: "https://i.pravatar.cc/150?img=59",
  },
  {
    id: 10,
    name: "John Wick",
    category: "Servicing",
    service: "TV Mounting & Wiring",
    rating: 5.0,
    reviewCount: 99,
    price: 900,
    image: "https://i.pravatar.cc/150?img=60",
  },
  {
    id: 11,
    name: "Gary Roach",
    category: "Servicing",
    service: "Pest Control & Spraying",
    rating: 3.2,
    reviewCount: 45,
    price: 1100,
    image: "https://i.pravatar.cc/150?img=51",
  },

  // --- FACIALS ---
  {
    id: 12,
    name: "Clara Woods",
    category: "Facials",
    service: "Glow & Hydrate Facial",
    rating: 4.9,
    reviewCount: 167,
    price: 450,
    image: "https://i.pravatar.cc/150?img=5",
  },
  {
    id: 13,
    name: "Samantha Jones",
    category: "Facials",
    service: "Anti-Aging Gold Treatment",
    rating: 4.8,
    reviewCount: 92,
    price: 1400,
    image: "https://i.pravatar.cc/150?img=44",
  },
  {
    id: 14,
    name: "Kelly Kapoor",
    category: "Facials",
    service: "Acne Clearing Facial",
    rating: 4.3,
    reviewCount: 118,
    price: 650,
    image: "https://i.pravatar.cc/150?img=45",
  },
  {
    id: 15,
    name: "Zendaya Coleman",
    category: "Facials",
    service: "Express 15-Min Mini Facial",
    rating: 4.1,
    reviewCount: 304,
    price: 300,
    image: "https://i.pravatar.cc/150?img=47",
  },

  // --- CLEANING ---
  {
    id: 16,
    name: "Maria Garcia",
    category: "Cleaning",
    service: "Deep House Cleaning",
    rating: 4.9,
    reviewCount: 423,
    price: 1600,
    image: "https://i.pravatar.cc/150?img=41",
  },
  {
    id: 17,
    name: "Levi Ackerman",
    category: "Cleaning",
    service: "Move-Out Spotless Clean",
    rating: 5.0,
    reviewCount: 150,
    price: 1905,
    image: "https://i.pravatar.cc/150?img=13",
  },
  {
    id: 18,
    name: "Consuela",
    category: "Cleaning",
    service: "Standard Room Cleaning",
    rating: 4.4,
    reviewCount: 276,
    price: 750,
    image: "https://i.pravatar.cc/150?img=20",
  },
  {
    id: 19,
    name: "Dexter Morgan",
    category: "Cleaning",
    service: "Power Washing Driveways",
    rating: 4.7,
    reviewCount: 64,
    price: 1300,
    image: "https://i.pravatar.cc/150?img=54",
  },
  {
    id: 20,
    name: "Arthur Dent",
    category: "Cleaning",
    service: "Window Washing (Exterior)",
    rating: 3.9,
    reviewCount: 88,
    price: 550,
    image: "https://i.pravatar.cc/150?img=52",
  },

  // --- BEAUTY ---
  {
    id: 21,
    name: "Edward Scissorhands",
    category: "Beauty",
    service: "Men's Haircut & Beard",
    rating: 4.5,
    reviewCount: 532,
    price: 450,
    image: "https://i.pravatar.cc/150?img=56",
  },
  {
    id: 22,
    name: "Elle Woods",
    category: "Beauty",
    service: "Women's Blowout & Style",
    rating: 4.8,
    reviewCount: 194,
    price: 800,
    image: "https://i.pravatar.cc/150?img=35",
  },
  {
    id: 23,
    name: "RuPaul",
    category: "Beauty",
    service: "Full Glam Makeup Application",
    rating: 5.0,
    reviewCount: 1205,
    price: 1500,
    image: "https://i.pravatar.cc/150?img=36",
  },
  {
    id: 24,
    name: "Haley Dunphy",
    category: "Beauty",
    service: "Manicure & Pedicure Combo",
    rating: 4.2,
    reviewCount: 143,
    price: 550,
    image: "https://i.pravatar.cc/150?img=32",
  },
];
